/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// v_yolo
// This file was @generated by ai8xize.py --test-dir /Users/yushanhuang/Documents/YUSHAN_JOSH/ai8x-synthesis/model --prefix v_yolo --checkpoint-file /Users/yushanhuang/Documents/YUSHAN_JOSH/verified_model/yolo/yolov1-q.pth.tar --config-file /Users/yushanhuang/Documents/YUSHAN_JOSH/verified_model/yolo/ai85-yolo-96-hwc.yaml --sample-input /Users/yushanhuang/Documents/YUSHAN_JOSH/ai8x-synthesis/tests/yolo_96.npy --device MAX78000 --timer 0 --display-checkpoint --verbose --overlap-data --mlator --max-checklines 8192 --new-kernel-loader --fifo --overwrite --device MAX78000 --timer 0 --display-checkpoint --verbose

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"
#include "timer.h"

#include "gcfr_regs.h"
#include "fcr_regs.h"
#include "sema_regs.h"

#include "tmr_revb.h"
#include <math.h>
#include <stdint.h>

#define TMR MXC_TMR2
volatile uint32_t cnn_time; // Stopwatch


void my_timer_initial()
{
    mxc_tmr_cfg_t cfg;
    cfg.pres = MXC_TMR_PRES_32;
    cfg.mode = MXC_TMR_MODE_ONESHOT;
    cfg.bitMode = MXC_TMR_BIT_MODE_32;
    cfg.clock = MXC_TMR_60M_CLK;
    cfg.cmp_cnt = 0xFFFFFFFF;
    cfg.pol = 0;
    MXC_TMR_Init(TMR, &cfg, false);
    MXC_TMR_Start(TMR);
}

void softmax_baseline(const float *vec_in, const uint16_t dim_vec, float *p_out)
{
    float sum = 0.0f;
    int16_t i;

    for (i = 0; i < dim_vec; i++)
    {
        p_out[i] = expf(vec_in[i]);
        sum += p_out[i];
    }

    for (i = 0; i < dim_vec; i++)
    {
        p_out[i] /= sum;
    }
}


void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// Data input: HWC 3x96x96 (27648 bytes total / 9216 bytes per channel):
static const uint32_t input_0[] = SAMPLE_INPUT_0;
void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  int i;
  const uint32_t *in0 = input_0;

  for (i = 0; i < 9216; i++) {
    // Remove the following line if there is no risk that the source would overrun the FIFO:
    while (((*((volatile uint32_t *) 0x50000004) & 1)) != 0); // Wait for FIFO 0
    *((volatile uint32_t *) 0x50000008) = *in0++; // Write FIFO 0
  }
}

// Expected output of layer 19 for v_yolo given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }
  // Truncated further checks...
  // Truncated further checks...

  return CNN_OK;
}

// Customize the basic softmax
static float ml_data[CNN_NUM_OUTPUTS];
static float ml_softmax[CNN_NUM_OUTPUTS];

void softmax_layer(void)
{
    cnn_unload((uint32_t *)ml_data);
    softmax_baseline(ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{


  MXC_ICC_Enable(MXC_ICC0); // Enable cache
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  // Configure Timer
  my_timer_initial();
  uint32_t prescale = (TMR->ctrl0 & MXC_F_TMR_REVB_CTRL0_CLKDIV_A) >> MXC_F_TMR_REVB_CTRL0_CLKDIV_A_POS;
  uint32_t timer_clock = MXC_TMR_RevB_GetClockSourceFreq((mxc_tmr_revb_regs_t*)TMR);
  printf("prescale: %lu, timer_clock: %lu\n", prescale, timer_clock);
  uint32_t start_ticks_init, end_ticks_init, elapsed_time_init, start_ticks_memory, end_ticks_memory, elapsed_time_memory, start_ticks_cnn, end_ticks_cnn, elapsed_time_cnn, start_ticks_cpu, end_ticks_cpu, elapsed_time_cpu;

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed


  printf("\n*** CNN Inference Test v_nas ***\n");
  printf("Num outputs: %d\n", CNN_NUM_OUTPUTS);


  // ***************************** Initialization ***************************** //

  start_ticks_init = TMR->cnt;

  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);
  cnn_boost_enable(MXC_GPIO2, MXC_GPIO_PIN_5); // Turn on the boost circuit
  cnn_init(); // Bring state machine into consistent state

  end_ticks_init = TMR->cnt;
  elapsed_time_init = (end_ticks_init - start_ticks_init) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);



  // ***************************** Memory I/O ***************************** //
  start_ticks_memory = TMR->cnt;

  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  cnn_start(); // Start CNN processing
  load_input(); // Load data input

  end_ticks_memory = TMR->cnt;
  elapsed_time_memory = (end_ticks_memory - start_ticks_memory) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);


  // ***************************** Inference ***************************** //
  start_ticks_cnn = TMR->cnt;

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN
  cnn_boost_disable(MXC_GPIO2, MXC_GPIO_PIN_5); // Turn off the boost circuit

  end_ticks_cnn = TMR->cnt;
  elapsed_time_cnn = (end_ticks_cnn - start_ticks_cnn) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);

  
  // ***************************** Post-Processing ***************************** //
  start_ticks_cpu = TMR->cnt;

  softmax_layer();

  end_ticks_cpu = TMR->cnt;
  elapsed_time_cpu = (end_ticks_cpu - start_ticks_cpu) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);



  // ***************************** Finished ***************************** //
  cnn_disable(); // Shut down CNN clock, disable peripheral

  printf("\n*** PASS ***\n\n");


  printf("Initialization Time: %lu us\n", elapsed_time_init);
  printf("Memory I/O Time: %lu us\n", elapsed_time_memory);
  printf("Inference Time: %lu us\n", elapsed_time_cnn);
  printf("Post-Processing Time: %lu us\n", elapsed_time_cpu);


  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 22,910,976 ops (22,404,096 macc; 506,880 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 4,128,768 ops (3,981,312 macc; 147,456 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 5,492,736 ops (5,308,416 macc; 184,320 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 1,373,184 ops (1,327,104 macc; 46,080 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 2,672,640 ops (2,654,208 macc; 18,432 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 304,128 ops (294,912 macc; 9,216 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 2,672,640 ops (2,654,208 macc; 18,432 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 304,128 ops (294,912 macc; 9,216 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7: 2,672,640 ops (2,654,208 macc; 18,432 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8: 94,464 ops (73,728 macc; 20,736 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9: 668,160 ops (663,552 macc; 4,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10: 76,032 ops (73,728 macc; 2,304 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11: 668,160 ops (663,552 macc; 4,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 12: 76,032 ops (73,728 macc; 2,304 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13: 668,160 ops (663,552 macc; 4,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 14: 76,032 ops (73,728 macc; 2,304 comp; 0 add; 0 mul; 0 bitwise)
    Layer 15: 668,160 ops (663,552 macc; 4,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 16: 152,064 ops (147,456 macc; 4,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 17: 76,032 ops (73,728 macc; 2,304 comp; 0 add; 0 mul; 0 bitwise)
    Layer 18: 39,168 ops (36,864 macc; 2,304 comp; 0 add; 0 mul; 0 bitwise)
    Layer 19: 27,648 ops (27,648 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 42,352 bytes out of 442,368 bytes total (9.6%)
  Bias memory:   396 bytes out of 2,048 bytes total (19.3%)
*/

