/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// yolov1_qat
// This file was @generated by ai8xize.py --test-dir ../npu/max78000/ --prefix yolov1_qat --checkpoint-file trained/Yolov1_checkpoint-q8.pth.tar --config-file ../model/yolo/ai85-yolo-224-hwc.yaml --device MAX78000 --timer 0 --display-checkpoint --verbose --overlap-data --mlator --no-unload --max-checklines 8192 --new-kernel-loader --fifo --sample-input ../model/yolo/sample_yolov1.npy

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// Data input: HWC 3x224x224 (150528 bytes total / 50176 bytes per channel):
static const uint32_t input_0[] = SAMPLE_INPUT_0;
void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  int i;
  const uint32_t *in0 = input_0;

  for (i = 0; i < 50176; i++) {
    // Remove the following line if there is no risk that the source would overrun the FIFO:
    while (((*((volatile uint32_t *) 0x50000004) & 1)) != 0); // Wait for FIFO 0
    *((volatile uint32_t *) 0x50000008) = *in0++; // Write FIFO 0
  }
}

// Expected output of layer 23 for yolov1_qat given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }
  // Truncated further checks...
  // Truncated further checks...
  // Truncated further checks...
  // Truncated further checks...
  // Truncated further checks...
  // Truncated further checks...
  // Truncated further checks...
  // Truncated further checks...
  // Truncated further checks...

  return CNN_OK;
}

int main(void)
{
  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test yolov1_qat ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  cnn_start(); // Start CNN processing
  load_input(); // Load data input via FIFO

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN

  if (check_output() != CNN_OK) fail();

  printf("\n*** PASS ***\n\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate data loading and inference time: %u us\n\n", cnn_time);
#endif

  cnn_disable(); // Shut down CNN clock, disable peripheral


  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 429,002,448 ops (420,963,312 macc; 8,039,136 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 89,915,392 ops (86,704,128 macc; 3,211,264 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 176,920,576 ops (173,408,256 macc; 3,512,320 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 11,189,248 ops (10,838,016 macc; 351,232 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 14,551,040 ops (14,450,688 macc; 100,352 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 3,311,616 ops (3,211,264 macc; 100,352 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 58,003,456 ops (57,802,752 macc; 200,704 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 1,831,424 ops (1,605,632 macc; 225,792 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7: 14,500,864 ops (14,450,688 macc; 50,176 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8: 1,630,720 ops (1,605,632 macc; 25,088 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9: 14,500,864 ops (14,450,688 macc; 50,176 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10: 1,630,720 ops (1,605,632 macc; 25,088 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11: 14,500,864 ops (14,450,688 macc; 50,176 comp; 0 add; 0 mul; 0 bitwise)
    Layer 12: 457,856 ops (401,408 macc; 56,448 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13: 3,625,216 ops (3,612,672 macc; 12,544 comp; 0 add; 0 mul; 0 bitwise)
    Layer 14: 407,680 ops (401,408 macc; 6,272 comp; 0 add; 0 mul; 0 bitwise)
    Layer 15: 3,625,216 ops (3,612,672 macc; 12,544 comp; 0 add; 0 mul; 0 bitwise)
    Layer 16: 7,237,888 ops (7,225,344 macc; 12,544 comp; 0 add; 0 mul; 0 bitwise)
    Layer 17: 7,237,888 ops (7,225,344 macc; 12,544 comp; 0 add; 0 mul; 0 bitwise)
    Layer 18: 1,822,016 ops (1,806,336 macc; 15,680 comp; 0 add; 0 mul; 0 bitwise)
    Layer 19: 1,809,472 ops (1,806,336 macc; 3,136 comp; 0 add; 0 mul; 0 bitwise)
    Layer 20: 203,840 ops (200,704 macc; 3,136 comp; 0 add; 0 mul; 0 bitwise)
    Layer 21: 50,960 ops (50,176 macc; 784 comp; 0 add; 0 mul; 0 bitwise)
    Layer 22: 13,328 ops (12,544 macc; 784 comp; 0 add; 0 mul; 0 bitwise)
    Layer 23: 24,304 ops (24,304 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 298,800 bytes out of 442,368 bytes total (67.5%)
  Bias memory:   991 bytes out of 2,048 bytes total (48.4%)
*/

