/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// yolo_test
// This file was @generated by ai8x-synthesis/ai8xize.py --avg-pool-rounding --config-file model/yolo/ai85-yolo-96-hwc.yaml --prefix yolo_test --test-dir model/yolo/test --board-name EvKit_V1 --fifo --checkpoint-file=model/yolo/yolov1.pth.tar --sample-input=data_sample_int.npy --device=MAX78000

// DO NOT EDIT - regenerate this file instead!

// Configuring 20 layers
// Input data: HWC
// Layer 0: 3x96x96 streaming, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x96x96 output
// Layer 1: 16x96x96 streaming, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x48x48 output
// Layer 2: 16x48x48 streaming, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x24x24 output
// Layer 3: 16x24x24, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x24x24 output
// Layer 4: 32x24x24, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x24x24 output
// Layer 5: 16x24x24, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x24x24 output
// Layer 6: 32x24x24, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x24x24 output
// Layer 7: 16x24x24, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x24x24 output
// Layer 8: 32x24x24, max pool 2x2 with stride 2/2, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 9: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 10: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 11: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 12: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 13: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 14: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 15: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 16: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 32x12x12 output
// Layer 17: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 18: 16x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 19: 16x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, no activation, 12x12x12 output

// Final Scales: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0}

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | (1<<14) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

