/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// v_nas_riscv
// This file was @generated by ai8xize.py --test-dir /Users/yushanhuang/Documents/YUSHAN_JOSH/ai8x-synthesis/model --prefix v_nas_riscv --checkpoint-file trained/ai85-cifar10-qat8-q.pth.tar --config-file networks/cifar10-nas.yaml --sample-input tests/sample_cifar-10.npy --boost 2.5 --overwrite --device MAX78000 --timer 0 --display-checkpoint --verbose --riscv --riscv-debug

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "fcr_regs.h"
#include "sema_regs.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"


#include <math.h>
#include <stdint.h>
#define TMR MXC_TMR2

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 3-channel 32x32 data input (3072 bytes total / 1024 bytes per channel):
// CHW 32x32, channel 0
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_0[] = SAMPLE_INPUT_0;

// CHW 32x32, channel 1
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_16[] = SAMPLE_INPUT_16;

// CHW 32x32, channel 2
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_32[] = SAMPLE_INPUT_32;

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x50400000, input_0, 256);
  memcpy32((uint32_t *) 0x50800000, input_16, 256);
  memcpy32((uint32_t *) 0x50c00000, input_32, 256);
}

// Expected output of layer 10 (fc_Gemm_4) for v_nas_riscv given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}


void softmax_baseline(const float *vec_in, const uint16_t dim_vec, float *p_out)
{
    float sum = 0.0f;
    int16_t i;

    for (i = 0; i < dim_vec; i++)
    {
        p_out[i] = expf(vec_in[i]);
        sum += p_out[i];
    }

    for (i = 0; i < dim_vec; i++)
    {
        p_out[i] /= sum;
    }
}
// Customize the basic softmax
static float ml_data[CNN_NUM_OUTPUTS];
static float ml_softmax[CNN_NUM_OUTPUTS];

void softmax_layer(void)
{
    cnn_unload((uint32_t *)ml_data);
    softmax_baseline(ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{
  Debug_Init(); // Set up RISCV JTAG
  MXC_ICC_Enable(MXC_ICC1); // Enable cache

  uint32_t prescale = 5;
  uint32_t timer_clock = ISO_FREQ;
  printf("prescale: %lu, timer_clock: %lu\n", prescale, timer_clock);
  uint32_t start_ticks_init, end_ticks_init, elapsed_time_init, start_ticks_memory, end_ticks_memory, elapsed_time_memory, start_ticks_cnn, end_ticks_cnn, elapsed_time_cnn, start_ticks_cpu, end_ticks_cpu, elapsed_time_cpu;

  printf("\n*** CNN Inference Test v_nas_riscv ***\n");


  // ***************************** Initialization ***************************** //



  start_ticks_init = TMR->cnt;
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);
  cnn_boost_enable(MXC_GPIO2, MXC_GPIO_PIN_5); // Turn on the boost circuit
  cnn_init(); // Bring state machine into consistent state

  end_ticks_init = TMR->cnt;
  elapsed_time_init = (end_ticks_init - start_ticks_init) * (1 << (prescale & 0xF)) / (timer_clock / 1000000); 


  // ***************************** Memory I/O ***************************** //

  start_ticks_memory = TMR->cnt;


  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  load_input(); // Load data input

  end_ticks_memory = TMR->cnt;
  elapsed_time_memory = (end_ticks_memory - start_ticks_memory) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);


  // ***************************** Inference ***************************** //


  start_ticks_cnn = TMR->cnt;
  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    asm volatile("wfi"); // Wait for CNN

  cnn_boost_disable(MXC_GPIO2, MXC_GPIO_PIN_5); // Turn off the boost circuit

  end_ticks_cnn = TMR->cnt;
  elapsed_time_cnn = (end_ticks_cnn - start_ticks_cnn) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);



  // ***************************** Post-Processing ***************************** //
  


  start_ticks_cpu = TMR->cnt;

  softmax_layer();

  end_ticks_cpu = TMR->cnt;
  elapsed_time_cpu = (end_ticks_cpu - start_ticks_cpu) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);
  printf("Post-Processing Time: %lu us\n", elapsed_time_cpu);


  // ***************************** Finished ***************************** //
  cnn_disable(); // Shut down CNN clock, disable peripheral

  printf("\n*** PASS ***\n\n");
  printf("Initialization Time: %lu us\n", elapsed_time_init);
  printf("Memory I/O Time: %lu us\n", elapsed_time_memory);
  printf("Inference Time: %lu us\n", elapsed_time_cnn);
  printf("Post-Processing Time: %lu us\n", elapsed_time_cpu);


  // Signal the Cortex-M4
  MXC_SEMA->irq0 = MXC_F_SEMA_IRQ0_EN | MXC_F_SEMA_IRQ0_CM4_IRQ;

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 36,481,536 ops (36,180,992 macc; 300,544 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0 (conv1_1_Conv_4): 1,835,008 ops (1,769,472 macc; 65,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1 (conv1_2_Conv_4): 2,129,920 ops (2,097,152 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2 (conv1_3_Conv_4): 18,939,904 ops (18,874,368 macc; 65,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3 (conv2_1_Conv_4): 4,792,320 ops (4,718,592 macc; 73,728 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4 (conv2_2_Conv_4): 540,672 ops (524,288 macc; 16,384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5 (conv3_1_Conv_4): 4,743,168 ops (4,718,592 macc; 24,576 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6 (conv3_2_Conv_4): 1,056,768 ops (1,048,576 macc; 8,192 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7 (conv4_1_Conv_4): 1,188,864 ops (1,179,648 macc; 9,216 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8 (conv4_2_Conv_4): 1,181,696 ops (1,179,648 macc; 2,048 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9 (conv5_1_Conv_4): 68,096 ops (65,536 macc; 2,560 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10 (fc_Gemm_4): 5,120 ops (5,120 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 301,760 bytes out of 442,368 bytes total (68.2%)
  Bias memory:   842 bytes out of 2,048 bytes total (41.1%)
*/

