#ifndef APP_SCENARIO_ALLON_SENSOR_TFLM_COMMON_CONFIG_H_
#define APP_SCENARIO_ALLON_SENSOR_TFLM_COMMON_CONFIG_H_

#define FLASH_XIP_MODEL 0
#define MEM_FREE_POS		(BOOT2NDLOADER_BASE) ////0x3401F000

#endif 
