/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// v_yolo
// This file was @generated by ai8xize.py --test-dir /Users/yushanhuang/Documents/YUSHAN_JOSH/ai8x-synthesis/model --prefix v_yolo --checkpoint-file /Users/yushanhuang/Documents/YUSHAN_JOSH/verified_model/yolo/yolov1-q.pth.tar --config-file /Users/yushanhuang/Documents/YUSHAN_JOSH/verified_model/yolo/ai85-yolo-96-hwc.yaml --sample-input /Users/yushanhuang/Documents/YUSHAN_JOSH/ai8x-synthesis/tests/yolo_96.npy --device MAX78000 --timer 0 --display-checkpoint --verbose --overlap-data --mlator --max-checklines 8192 --new-kernel-loader --fifo --overwrite --device MAX78000 --timer 0 --display-checkpoint --verbose

// DO NOT EDIT - regenerate this file instead!

// Configuring 20 layers
// Input data: HWC
// Layer 0: 3x96x96 streaming, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x96x96 output
// Layer 1: 16x96x96 streaming, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x48x48 output
// Layer 2: 16x48x48 streaming, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x24x24 output
// Layer 3: 16x24x24, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x24x24 output
// Layer 4: 32x24x24, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x24x24 output
// Layer 5: 16x24x24, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x24x24 output
// Layer 6: 32x24x24, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x24x24 output
// Layer 7: 16x24x24, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x24x24 output
// Layer 8: 32x24x24, max pool 2x2 with stride 2/2, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 9: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 10: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 11: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 12: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 13: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 14: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 15: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x12x12 output
// Layer 16: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 32x12x12 output
// Layer 17: 32x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 18: 16x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 19: 16x12x12, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, no activation, 12x12x12 output

// Final Scales: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0}

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | (1<<14) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | (1<<14) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 108);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 96);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 96);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 96);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x00000013; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x00000013; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x00000013; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00108008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x00000013; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50100090) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50100310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50100690) = 0x0000005f; // TRAM ptr max
  *((volatile uint32_t *) 0x50100790) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0x00070007; // Mask and processor enables
  *((volatile uint32_t *) 0x50100810) = 0x00000001; // Stream processing start
  *((volatile uint32_t *) 0x50100910) = 0x00000002; // Rollover
  *((volatile uint32_t *) 0x50100990) = 0x00002400; // Input frame size

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50500090) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50500310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50500690) = 0x0000005f; // TRAM ptr max
  *((volatile uint32_t *) 0x50500790) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500810) = 0x00000001; // Stream processing start
  *((volatile uint32_t *) 0x50500910) = 0x00000002; // Rollover
  *((volatile uint32_t *) 0x50500990) = 0x00002400; // Input frame size

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50900090) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50900310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50900690) = 0x0000005f; // TRAM ptr max
  *((volatile uint32_t *) 0x50900790) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900810) = 0x00000001; // Stream processing start
  *((volatile uint32_t *) 0x50900910) = 0x00000002; // Rollover
  *((volatile uint32_t *) 0x50900990) = 0x00002400; // Input frame size

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50d00090) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50d00310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50d00690) = 0x0000005f; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00790) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00810) = 0x00000001; // Stream processing start
  *((volatile uint32_t *) 0x50d00910) = 0x00000002; // Rollover
  *((volatile uint32_t *) 0x50d00990) = 0x00002400; // Input frame size

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50100094) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50100194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100314) = 0x00018c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x008000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100694) = 0x0060008f; // TRAM ptr max
  *((volatile uint32_t *) 0x50100794) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50100714) = 0xffffffff; // Mask and processor enables
  *((volatile uint32_t *) 0x50100814) = 0x0000012c; // Stream processing start
  *((volatile uint32_t *) 0x50100894) = 0x00640021; // Stream processing delta
  *((volatile uint32_t *) 0x50100914) = 0x0000018e; // Rollover

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50500094) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50500194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500314) = 0x00018c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x008000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500694) = 0x0060008f; // TRAM ptr max
  *((volatile uint32_t *) 0x50500794) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50500814) = 0x0000012c; // Stream processing start
  *((volatile uint32_t *) 0x50500894) = 0x00640021; // Stream processing delta
  *((volatile uint32_t *) 0x50500914) = 0x0000018e; // Rollover

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50900094) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50900194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900314) = 0x00018c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x008000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900694) = 0x0060008f; // TRAM ptr max
  *((volatile uint32_t *) 0x50900794) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50900814) = 0x0000012c; // Stream processing start
  *((volatile uint32_t *) 0x50900894) = 0x00640021; // Stream processing delta
  *((volatile uint32_t *) 0x50900914) = 0x0000018e; // Rollover

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x00010061; // Rows
  *((volatile uint32_t *) 0x50d00094) = 0x00010061; // Columns
  *((volatile uint32_t *) 0x50d00194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00314) = 0x00018c00; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x008000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00694) = 0x0060008f; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00794) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50d00814) = 0x0000012c; // Stream processing start
  *((volatile uint32_t *) 0x50d00894) = 0x00640021; // Stream processing delta
  *((volatile uint32_t *) 0x50d00914) = 0x0000018e; // Rollover

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x00010031; // Rows
  *((volatile uint32_t *) 0x50100098) = 0x00010031; // Columns
  *((volatile uint32_t *) 0x50100198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100518) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50100598) = 0x00008ba0; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50100698) = 0x009000a7; // TRAM ptr max
  *((volatile uint32_t *) 0x50100798) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100818) = 0x0000009c; // Stream processing start
  *((volatile uint32_t *) 0x50100898) = 0x00340022; // Stream processing delta
  *((volatile uint32_t *) 0x50100918) = 0x000000ce; // Rollover

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x00010031; // Rows
  *((volatile uint32_t *) 0x50500098) = 0x00010031; // Columns
  *((volatile uint32_t *) 0x50500198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500518) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50500598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50500698) = 0x009000a7; // TRAM ptr max
  *((volatile uint32_t *) 0x50500798) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500818) = 0x0000009c; // Stream processing start
  *((volatile uint32_t *) 0x50500898) = 0x00340022; // Stream processing delta
  *((volatile uint32_t *) 0x50500918) = 0x000000ce; // Rollover

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x00010031; // Rows
  *((volatile uint32_t *) 0x50900098) = 0x00010031; // Columns
  *((volatile uint32_t *) 0x50900198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900518) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50900598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50900698) = 0x009000a7; // TRAM ptr max
  *((volatile uint32_t *) 0x50900798) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900818) = 0x0000009c; // Stream processing start
  *((volatile uint32_t *) 0x50900898) = 0x00340022; // Stream processing delta
  *((volatile uint32_t *) 0x50900918) = 0x000000ce; // Rollover

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x00010031; // Rows
  *((volatile uint32_t *) 0x50d00098) = 0x00010031; // Columns
  *((volatile uint32_t *) 0x50d00198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00518) = 0x00000c00; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x00000078; // Mask offset and count
  *((volatile uint32_t *) 0x50d00698) = 0x009000a7; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00798) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d00718) = 0xffffffff; // Mask and processor enables
  *((volatile uint32_t *) 0x50d00818) = 0x0000009c; // Stream processing start
  *((volatile uint32_t *) 0x50d00898) = 0x00340022; // Stream processing delta
  *((volatile uint32_t *) 0x50d00918) = 0x000000ce; // Rollover

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x5010009c) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010051c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x5010059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x5010069c) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x5010079c) = 0x0002b000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x5050009c) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050051c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x5050069c) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x5050079c) = 0x0002a000; // Post processing register

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x5090009c) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090051c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x5090069c) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x5090079c) = 0x0002a000; // Post processing register

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50d0009c) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0051c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x010001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0069c) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x50d0079c) = 0x0002a000; // Post processing register

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501000a0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50100320) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003a0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a0) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x12001278; // Mask offset and count
  *((volatile uint32_t *) 0x50100120) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007a0) = 0x00029040; // Post processing register
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x505000a0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50500320) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003a0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x12001278; // Mask offset and count
  *((volatile uint32_t *) 0x50500120) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007a0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x509000a0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50900320) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003a0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x12001278; // Mask offset and count
  *((volatile uint32_t *) 0x50900120) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007a0) = 0x00028000; // Post processing register

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d000a0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50d00320) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003a0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x12001278; // Mask offset and count
  *((volatile uint32_t *) 0x50d00120) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007a0) = 0x00028000; // Post processing register

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x501000a4) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x50100324) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a4) = 0x0000ab20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x00800178; // Mask offset and count
  *((volatile uint32_t *) 0x501006a4) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a4) = 0x0002a000; // Post processing register

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x505000a4) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x50500324) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x00800178; // Mask offset and count
  *((volatile uint32_t *) 0x505006a4) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a4) = 0x0002b000; // Post processing register

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x509000a4) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x50900324) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x00800178; // Mask offset and count
  *((volatile uint32_t *) 0x509006a4) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a4) = 0x0002a000; // Post processing register

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50d000a4) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x50d00324) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x00800178; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a4) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a4) = 0x0002a000; // Post processing register
  *((volatile uint32_t *) 0x50d00724) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501000a8) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50100328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x0d800df8; // Mask offset and count
  *((volatile uint32_t *) 0x50100128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007a8) = 0x00028000; // Post processing register

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x505000a8) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50500328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x0d800df8; // Mask offset and count
  *((volatile uint32_t *) 0x50500128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007a8) = 0x00029040; // Post processing register

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x509000a8) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50900328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x0d800df8; // Mask offset and count
  *((volatile uint32_t *) 0x50900128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007a8) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50900728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d000a8) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50d00328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x0d800df8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007a8) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50d00728) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x501000ac) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ac) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x02200318; // Mask offset and count
  *((volatile uint32_t *) 0x501006ac) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x501007ac) = 0x0002a000; // Post processing register
  *((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x505000ac) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x02200318; // Mask offset and count
  *((volatile uint32_t *) 0x505006ac) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x505007ac) = 0x0002a000; // Post processing register

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x509000ac) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x02200318; // Mask offset and count
  *((volatile uint32_t *) 0x509006ac) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x509007ac) = 0x0002b000; // Post processing register

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50d000ac) = 0x00010019; // Columns
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x02200318; // Mask offset and count
  *((volatile uint32_t *) 0x50d006ac) = 0x00000017; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007ac) = 0x0002a000; // Post processing register

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501000b0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x501001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100330) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003b0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b0) = 0x00006ba0; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x1c201c98; // Mask offset and count
  *((volatile uint32_t *) 0x50100130) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007b0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50100730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x505000b0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x505001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500330) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003b0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x1c201c98; // Mask offset and count
  *((volatile uint32_t *) 0x50500130) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007b0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x509000b0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x509001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900330) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003b0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x1c201c98; // Mask offset and count
  *((volatile uint32_t *) 0x50900130) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007b0) = 0x00029040; // Post processing register

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d000b0) = 0x00000017; // Columns
  *((volatile uint32_t *) 0x50d001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00230) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00330) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003b0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x1c201c98; // Mask offset and count
  *((volatile uint32_t *) 0x50d00130) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007b0) = 0x00028000; // Post processing register

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100034) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x501000b4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50100334) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b4) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100634) = 0x01a00298; // Mask offset and count
  *((volatile uint32_t *) 0x501006b4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b4) = 0x0002a000; // Post processing register

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500034) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x505000b4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50500334) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500634) = 0x01a00298; // Mask offset and count
  *((volatile uint32_t *) 0x505006b4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b4) = 0x0002a000; // Post processing register

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900034) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x509000b4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50900334) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900634) = 0x01a00298; // Mask offset and count
  *((volatile uint32_t *) 0x509006b4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b4) = 0x0002a000; // Post processing register

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00034) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x50d000b4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50d00334) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a34) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00634) = 0x01a00298; // Mask offset and count
  *((volatile uint32_t *) 0x50d006b4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b4) = 0x0002b000; // Post processing register
  *((volatile uint32_t *) 0x50d00734) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 0
  *((volatile uint32_t *) 0x50100038) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000b8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50100338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b8) = 0x0000cb20; // Layer control
  *((volatile uint32_t *) 0x50100a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100638) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50100138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007b8) = 0x00028000; // Post processing register

  // Layer 10 quadrant 1
  *((volatile uint32_t *) 0x50500038) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000b8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50500338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500638) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50500138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007b8) = 0x00028000; // Post processing register

  // Layer 10 quadrant 2
  *((volatile uint32_t *) 0x50900038) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000b8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50900338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900638) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50900138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007b8) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50900738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 3
  *((volatile uint32_t *) 0x50d00038) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000b8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d00338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00638) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50d00138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007b8) = 0x00029040; // Post processing register
  *((volatile uint32_t *) 0x50d00738) = 0xffffffff; // Mask and processor enables

  // Layer 11 quadrant 0
  *((volatile uint32_t *) 0x5010003c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x501000bc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x5010043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005bc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a3c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5010063c) = 0x03400438; // Mask offset and count
  *((volatile uint32_t *) 0x501006bc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x501007bc) = 0x0002b020; // Post processing register
  *((volatile uint32_t *) 0x5010073c) = 0xffffffff; // Mask and processor enables

  // Layer 11 quadrant 1
  *((volatile uint32_t *) 0x5050003c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x505000bc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x5050043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005bc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a3c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5050063c) = 0x03400438; // Mask offset and count
  *((volatile uint32_t *) 0x505006bc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x505007bc) = 0x0002a000; // Post processing register

  // Layer 11 quadrant 2
  *((volatile uint32_t *) 0x5090003c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x509000bc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x5090043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005bc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a3c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5090063c) = 0x03400438; // Mask offset and count
  *((volatile uint32_t *) 0x509006bc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x509007bc) = 0x0002a000; // Post processing register

  // Layer 11 quadrant 3
  *((volatile uint32_t *) 0x50d0003c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x50d000bc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50d0043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005bc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a3c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0063c) = 0x03400438; // Mask offset and count
  *((volatile uint32_t *) 0x50d006bc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007bc) = 0x0002a000; // Post processing register

  // Layer 12 quadrant 0
  *((volatile uint32_t *) 0x50100040) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000c0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50100340) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003c0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005c0) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a40) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100640) = 0x264026b8; // Mask offset and count
  *((volatile uint32_t *) 0x50100140) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007c0) = 0x00029050; // Post processing register
  *((volatile uint32_t *) 0x50100740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 1
  *((volatile uint32_t *) 0x50500040) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000c0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50500340) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003c0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005c0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a40) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500640) = 0x264026b8; // Mask offset and count
  *((volatile uint32_t *) 0x50500140) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007c0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50500740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 2
  *((volatile uint32_t *) 0x50900040) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000c0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50900340) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003c0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005c0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a40) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900640) = 0x264026b8; // Mask offset and count
  *((volatile uint32_t *) 0x50900140) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007c0) = 0x00028000; // Post processing register

  // Layer 12 quadrant 3
  *((volatile uint32_t *) 0x50d00040) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000c0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d00340) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003c0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005c0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a40) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00640) = 0x264026b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00140) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007c0) = 0x00028000; // Post processing register

  // Layer 13 quadrant 0
  *((volatile uint32_t *) 0x50100044) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x501000c4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50100344) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100544) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c4) = 0x0000ab20; // Layer control
  *((volatile uint32_t *) 0x50100a44) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100644) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x501006c4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x501007c4) = 0x0002a000; // Post processing register

  // Layer 13 quadrant 1
  *((volatile uint32_t *) 0x50500044) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x505000c4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50500344) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500544) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a44) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500644) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x505006c4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x505007c4) = 0x0002b020; // Post processing register

  // Layer 13 quadrant 2
  *((volatile uint32_t *) 0x50900044) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x509000c4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50900344) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900544) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a44) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900644) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x509006c4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x509007c4) = 0x0002a000; // Post processing register

  // Layer 13 quadrant 3
  *((volatile uint32_t *) 0x50d00044) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x50d000c4) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50d00344) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00544) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a44) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00644) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006c4) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007c4) = 0x0002a000; // Post processing register
  *((volatile uint32_t *) 0x50d00744) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 0
  *((volatile uint32_t *) 0x50100048) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000c8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50100348) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003c8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005c8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100648) = 0x21c02238; // Mask offset and count
  *((volatile uint32_t *) 0x50100148) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007c8) = 0x00028000; // Post processing register

  // Layer 14 quadrant 1
  *((volatile uint32_t *) 0x50500048) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000c8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50500348) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003c8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500648) = 0x21c02238; // Mask offset and count
  *((volatile uint32_t *) 0x50500148) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007c8) = 0x00029050; // Post processing register

  // Layer 14 quadrant 2
  *((volatile uint32_t *) 0x50900048) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000c8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50900348) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003c8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900648) = 0x21c02238; // Mask offset and count
  *((volatile uint32_t *) 0x50900148) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007c8) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50900748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 3
  *((volatile uint32_t *) 0x50d00048) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000c8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d00348) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003c8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00648) = 0x21c02238; // Mask offset and count
  *((volatile uint32_t *) 0x50d00148) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007c8) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50d00748) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 0
  *((volatile uint32_t *) 0x5010004c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x501000cc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x5010044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010054c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005cc) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a4c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5010064c) = 0x04600558; // Mask offset and count
  *((volatile uint32_t *) 0x501006cc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x501007cc) = 0x0002a000; // Post processing register
  *((volatile uint32_t *) 0x5010074c) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 1
  *((volatile uint32_t *) 0x5050004c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x505000cc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x5050044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050054c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a4c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5050064c) = 0x04600558; // Mask offset and count
  *((volatile uint32_t *) 0x505006cc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x505007cc) = 0x0002a000; // Post processing register

  // Layer 15 quadrant 2
  *((volatile uint32_t *) 0x5090004c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x509000cc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x5090044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090054c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a4c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5090064c) = 0x04600558; // Mask offset and count
  *((volatile uint32_t *) 0x509006cc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x509007cc) = 0x0002b020; // Post processing register

  // Layer 15 quadrant 3
  *((volatile uint32_t *) 0x50d0004c) = 0x0001000d; // Rows
  *((volatile uint32_t *) 0x50d000cc) = 0x0001000d; // Columns
  *((volatile uint32_t *) 0x50d0044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0054c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a4c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0064c) = 0x04600558; // Mask offset and count
  *((volatile uint32_t *) 0x50d006cc) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007cc) = 0x0002a000; // Post processing register

  // Layer 16 quadrant 0
  *((volatile uint32_t *) 0x50100050) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000d0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50100350) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003d0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005d0) = 0x0000ab20; // Layer control
  *((volatile uint32_t *) 0x50100a50) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100650) = 0x30603158; // Mask offset and count
  *((volatile uint32_t *) 0x50100150) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007d0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50100750) = 0xffffffff; // Mask and processor enables

  // Layer 16 quadrant 1
  *((volatile uint32_t *) 0x50500050) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000d0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50500350) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003d0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005d0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a50) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500650) = 0x30603158; // Mask offset and count
  *((volatile uint32_t *) 0x50500150) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007d0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50500750) = 0xffffffff; // Mask and processor enables

  // Layer 16 quadrant 2
  *((volatile uint32_t *) 0x50900050) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000d0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50900350) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003d0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005d0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a50) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900650) = 0x30603158; // Mask offset and count
  *((volatile uint32_t *) 0x50900150) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007d0) = 0x00028000; // Post processing register

  // Layer 16 quadrant 3
  *((volatile uint32_t *) 0x50d00050) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000d0) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d00350) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003d0) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005d0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a50) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00650) = 0x30603158; // Mask offset and count
  *((volatile uint32_t *) 0x50d00150) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007d0) = 0x00029020; // Post processing register

  // Layer 17 quadrant 0
  *((volatile uint32_t *) 0x50100054) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000d4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50100354) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003d4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005d4) = 0x0000cb20; // Layer control
  *((volatile uint32_t *) 0x50100a54) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100654) = 0x22e02358; // Mask offset and count
  *((volatile uint32_t *) 0x50100154) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007d4) = 0x00028000; // Post processing register

  // Layer 17 quadrant 1
  *((volatile uint32_t *) 0x50500054) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000d4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50500354) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003d4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a54) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500654) = 0x22e02358; // Mask offset and count
  *((volatile uint32_t *) 0x50500154) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007d4) = 0x00028000; // Post processing register

  // Layer 17 quadrant 2
  *((volatile uint32_t *) 0x50900054) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000d4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50900354) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003d4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a54) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900654) = 0x22e02358; // Mask offset and count
  *((volatile uint32_t *) 0x50900154) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007d4) = 0x00029050; // Post processing register
  *((volatile uint32_t *) 0x50900754) = 0xffffffff; // Mask and processor enables

  // Layer 17 quadrant 3
  *((volatile uint32_t *) 0x50d00054) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000d4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d00354) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003d4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a54) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00654) = 0x22e02358; // Mask offset and count
  *((volatile uint32_t *) 0x50d00154) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007d4) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50d00754) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 0
  *((volatile uint32_t *) 0x50100058) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000d8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50100358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003d8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005d8) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100658) = 0x24002478; // Mask offset and count
  *((volatile uint32_t *) 0x50100158) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007d8) = 0x00028000; // Post processing register

  // Layer 18 quadrant 1
  *((volatile uint32_t *) 0x50500058) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000d8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50500358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003d8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500658) = 0x24002478; // Mask offset and count
  *((volatile uint32_t *) 0x50500158) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007d8) = 0x00028000; // Post processing register

  // Layer 18 quadrant 2
  *((volatile uint32_t *) 0x50900058) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000d8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50900358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003d8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900658) = 0x24002478; // Mask offset and count
  *((volatile uint32_t *) 0x50900158) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007d8) = 0x00028000; // Post processing register

  // Layer 18 quadrant 3
  *((volatile uint32_t *) 0x50d00058) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000d8) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d00358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003d8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00658) = 0x24002478; // Mask offset and count
  *((volatile uint32_t *) 0x50d00158) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007d8) = 0x00029050; // Post processing register
  *((volatile uint32_t *) 0x50d00758) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 0
  *((volatile uint32_t *) 0x5010005c) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000dc) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x501003dc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010055c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005dc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100a5c) = 0x00005800; // Layer control 2
  *((volatile uint32_t *) 0x5010065c) = 0x318031d8; // Mask offset and count
  *((volatile uint32_t *) 0x5010015c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007dc) = 0x00025060; // Post processing register
  *((volatile uint32_t *) 0x5010075c) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 1
  *((volatile uint32_t *) 0x5050005c) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000dc) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x505003dc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050055c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005dc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a5c) = 0x00005800; // Layer control 2
  *((volatile uint32_t *) 0x5050065c) = 0x318031d8; // Mask offset and count
  *((volatile uint32_t *) 0x5050015c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007dc) = 0x00024000; // Post processing register

  // Layer 19 quadrant 2
  *((volatile uint32_t *) 0x5090005c) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000dc) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x509003dc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090055c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005dc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a5c) = 0x00005800; // Layer control 2
  *((volatile uint32_t *) 0x5090065c) = 0x318031d8; // Mask offset and count
  *((volatile uint32_t *) 0x5090015c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007dc) = 0x00024000; // Post processing register

  // Layer 19 quadrant 3
  *((volatile uint32_t *) 0x50d0005c) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000dc) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d003dc) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0055c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005dc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a5c) = 0x00005800; // Layer control 2
  *((volatile uint32_t *) 0x50d0065c) = 0x318031d8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0015c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007dc) = 0x00024000; // Post processing register


  *((volatile uint32_t *) 0x50000000) = 0x00001908; // FIFO control

  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x0018c808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x0018c809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x0018c809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x0018c809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x0018c809; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf32)
{
  uint16_t *out_buf = (uint16_t *) out_buf32;
  uint32_t val;
  volatile uint32_t *mlat, *ctrl;
  int i;
  uint32_t offs;

  // Custom unload for this network, layer 19: 8-bit data, shape: (12, 12, 12)
  ctrl = (volatile uint32_t *) 0x50100000;
  mlat = (volatile uint32_t *) 0x50101000;
  // Channel 0
  offs = 0x0000;
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00010008; // Enable mlator, byte 0
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 1
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00030008; // Enable mlator, byte 1
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 2
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00050008; // Enable mlator, byte 2
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 3
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00070008; // Enable mlator, byte 3
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 4
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00010008; // Enable mlator, byte 0
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 5
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00030008; // Enable mlator, byte 1
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 6
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00050008; // Enable mlator, byte 2
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 7
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00070008; // Enable mlator, byte 3
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 8
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00010008; // Enable mlator, byte 0
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 9
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00030008; // Enable mlator, byte 1
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 10
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00050008; // Enable mlator, byte 2
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator
  // Channel 11
  *((volatile uint32_t *) 0x50100310) = 0x00000000; // Set SRAM address
  *((volatile uint32_t *) 0x50100a10) = 0x00000000; // Set pointer increment
  *ctrl = 0x00070008; // Enable mlator, byte 3
  asm volatile ("" : "=m" (*mlat) : "r" (*mlat)); // Prime
  for (i = 0; i < 4; i++) {
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  }
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
    out_buf32[offs++] = *mlat;
  *ctrl = 0x00000008; // Disable mlator

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

