/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// v_autoenc_riscv
// This file was @generated by ai8xize.py --test-dir /Users/yushanhuang/Documents/YUSHAN_JOSH/ai8x-synthesis/model --prefix v_autoenc_riscv --checkpoint-file trained/ai85-autoencoder-samplemotordatalimerick-qat-q.pth.tar --config-file networks/ai85-autoencoder.yaml --device MAX78000 --sample-input tests/sample_motordatalimerick_fortrain.npy --boost 2.5 --device MAX78000 --timer 0 --display-checkpoint --verbose --riscv --riscv-debug

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "fcr_regs.h"
#include "sema_regs.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

#define TMR MXC_TMR2

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 256-channel 3x1 data input (768 bytes total / 3 bytes per channel):
// HWC 3x1, channels 0 to 3
// HWC 3x1, channels 64 to 67
// HWC 3x1, channels 128 to 131
// HWC 3x1, channels 192 to 195
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_0[] = SAMPLE_INPUT_0;

// HWC 3x1, channels 4 to 7
// HWC 3x1, channels 68 to 71
// HWC 3x1, channels 132 to 135
// HWC 3x1, channels 196 to 199
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_4[] = SAMPLE_INPUT_4;

// HWC 3x1, channels 8 to 11
// HWC 3x1, channels 72 to 75
// HWC 3x1, channels 136 to 139
// HWC 3x1, channels 200 to 203
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_8[] = SAMPLE_INPUT_8;

// HWC 3x1, channels 12 to 15
// HWC 3x1, channels 76 to 79
// HWC 3x1, channels 140 to 143
// HWC 3x1, channels 204 to 207
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_12[] = SAMPLE_INPUT_12;

// HWC 3x1, channels 16 to 19
// HWC 3x1, channels 80 to 83
// HWC 3x1, channels 144 to 147
// HWC 3x1, channels 208 to 211
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_16[] = SAMPLE_INPUT_16;

// HWC 3x1, channels 20 to 23
// HWC 3x1, channels 84 to 87
// HWC 3x1, channels 148 to 151
// HWC 3x1, channels 212 to 215
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_20[] = SAMPLE_INPUT_20;

// HWC 3x1, channels 24 to 27
// HWC 3x1, channels 88 to 91
// HWC 3x1, channels 152 to 155
// HWC 3x1, channels 216 to 219
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_24[] = SAMPLE_INPUT_24;

// HWC 3x1, channels 28 to 31
// HWC 3x1, channels 92 to 95
// HWC 3x1, channels 156 to 159
// HWC 3x1, channels 220 to 223
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_28[] = SAMPLE_INPUT_28;

// HWC 3x1, channels 32 to 35
// HWC 3x1, channels 96 to 99
// HWC 3x1, channels 160 to 163
// HWC 3x1, channels 224 to 227
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_32[] = SAMPLE_INPUT_32;

// HWC 3x1, channels 36 to 39
// HWC 3x1, channels 100 to 103
// HWC 3x1, channels 164 to 167
// HWC 3x1, channels 228 to 231
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_36[] = SAMPLE_INPUT_36;

// HWC 3x1, channels 40 to 43
// HWC 3x1, channels 104 to 107
// HWC 3x1, channels 168 to 171
// HWC 3x1, channels 232 to 235
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_40[] = SAMPLE_INPUT_40;

// HWC 3x1, channels 44 to 47
// HWC 3x1, channels 108 to 111
// HWC 3x1, channels 172 to 175
// HWC 3x1, channels 236 to 239
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_44[] = SAMPLE_INPUT_44;

// HWC 3x1, channels 48 to 51
// HWC 3x1, channels 112 to 115
// HWC 3x1, channels 176 to 179
// HWC 3x1, channels 240 to 243
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_48[] = SAMPLE_INPUT_48;

// HWC 3x1, channels 52 to 55
// HWC 3x1, channels 116 to 119
// HWC 3x1, channels 180 to 183
// HWC 3x1, channels 244 to 247
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_52[] = SAMPLE_INPUT_52;

// HWC 3x1, channels 56 to 59
// HWC 3x1, channels 120 to 123
// HWC 3x1, channels 184 to 187
// HWC 3x1, channels 248 to 251
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_56[] = SAMPLE_INPUT_56;

// HWC 3x1, channels 60 to 63
// HWC 3x1, channels 124 to 127
// HWC 3x1, channels 188 to 191
// HWC 3x1, channels 252 to 255
__attribute__ ((section(".rvflash_section")))
static const uint32_t input_60[] = SAMPLE_INPUT_60;

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x50400000, input_0, 12);
  memcpy32((uint32_t *) 0x50408000, input_4, 12);
  memcpy32((uint32_t *) 0x50410000, input_8, 12);
  memcpy32((uint32_t *) 0x50418000, input_12, 12);
  memcpy32((uint32_t *) 0x50800000, input_16, 12);
  memcpy32((uint32_t *) 0x50808000, input_20, 12);
  memcpy32((uint32_t *) 0x50810000, input_24, 12);
  memcpy32((uint32_t *) 0x50818000, input_28, 12);
  memcpy32((uint32_t *) 0x50c00000, input_32, 12);
  memcpy32((uint32_t *) 0x50c08000, input_36, 12);
  memcpy32((uint32_t *) 0x50c10000, input_40, 12);
  memcpy32((uint32_t *) 0x50c18000, input_44, 12);
  memcpy32((uint32_t *) 0x51000000, input_48, 12);
  memcpy32((uint32_t *) 0x51008000, input_52, 12);
  memcpy32((uint32_t *) 0x51010000, input_56, 12);
  memcpy32((uint32_t *) 0x51018000, input_60, 12);
}

// Expected output of layer 6 for v_autoenc_riscv given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

static int32_t ml_data[CNN_NUM_OUTPUTS];

int main(void)
{
  Debug_Init(); // Set up RISCV JTAG
  MXC_ICC_Enable(MXC_ICC1); // Enable cache


  uint32_t prescale = 5;
  uint32_t timer_clock = ISO_FREQ;
  printf("prescale: %lu, timer_clock: %lu\n", prescale, timer_clock);
  uint32_t start_ticks_init, end_ticks_init, elapsed_time_init, start_ticks_memory, end_ticks_memory, elapsed_time_memory, start_ticks_cnn, end_ticks_cnn, elapsed_time_cnn, start_ticks_cpu, end_ticks_cpu, elapsed_time_cpu;


  printf("\n*** CNN Inference Test v_autoenc_riscv ***\n");

  // ***************************** Initialization ***************************** //
  

  start_ticks_init = TMR->cnt;

  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);
  cnn_boost_enable(MXC_GPIO2, MXC_GPIO_PIN_5); // Turn on the boost circuit
  cnn_init(); // Bring state machine into consistent state

  end_ticks_init = TMR->cnt;
  elapsed_time_init = (end_ticks_init - start_ticks_init) * (1 << (prescale & 0xF)) / (timer_clock / 1000000); 
  
  // ***************************** Memory I/O ***************************** //

  start_ticks_memory = TMR->cnt;

  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  load_input(); // Load data input

  end_ticks_memory = TMR->cnt;
  elapsed_time_memory = (end_ticks_memory - start_ticks_memory) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);

  // ***************************** Inference ***************************** //


  start_ticks_cnn = TMR->cnt;

  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    asm volatile("wfi"); // Wait for CNN

  cnn_boost_disable(MXC_GPIO2, MXC_GPIO_PIN_5); // Turn off the boost circuit

  end_ticks_cnn = TMR->cnt;
  elapsed_time_cnn = (end_ticks_cnn - start_ticks_cnn) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);


  // ***************************** Post-Processing ***************************** //
  start_ticks_cpu = TMR->cnt;

  cnn_unload((uint32_t *) ml_data);

  end_ticks_cpu = TMR->cnt;
  elapsed_time_cpu = (end_ticks_cpu - start_ticks_cpu) * (1 << (prescale & 0xF)) / (timer_clock / 1000000);


  // ***************************** Finished ***************************** //
  cnn_disable(); // Shut down CNN clock, disable peripheral

  printf("\n*** PASS ***\n\n");
  printf("Initialization Time: %lu us\n", elapsed_time_init);
  printf("Memory I/O Time: %lu us\n", elapsed_time_memory);
  printf("Inference Time: %lu us\n", elapsed_time_cnn);
  printf("Post-Processing Time: %lu us\n", elapsed_time_cpu);
  
  
  // Signal the Cortex-M4
  MXC_SEMA->irq0 = MXC_F_SEMA_IRQ0_EN | MXC_F_SEMA_IRQ0_CM4_IRQ;

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 202,596 ops (201,984 macc; 612 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 98,688 ops (98,304 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 24,640 ops (24,576 macc; 64 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 2,080 ops (2,048 macc; 32 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 132 ops (128 macc; 4 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 160 ops (128 macc; 32 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 3,168 ops (3,072 macc; 96 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 73,728 ops (73,728 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 136,448 bytes out of 442,368 bytes total (30.8%)
  Bias memory:   352 bytes out of 2,048 bytes total (17.2%)
*/

