/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// ARM wrapper code
// v_autoenc_riscv
// This file was @generated by ai8xize.py --test-dir /Users/yushanhuang/Documents/YUSHAN_JOSH/ai8x-synthesis/model --prefix v_autoenc_riscv --checkpoint-file trained/ai85-autoencoder-samplemotordatalimerick-qat-q.pth.tar --config-file networks/ai85-autoencoder.yaml --device MAX78000 --sample-input tests/sample_motordatalimerick_fortrain.npy --boost 2.5 --device MAX78000 --timer 0 --display-checkpoint --verbose --riscv --riscv-debug

#include <stdlib.h>
#include <stdint.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "fcr_regs.h"
#include "sema_regs.h"

#include "tmr_revb.h"

#define TMR MXC_TMR2

extern volatile void const *__FlashStart_; // Defined in linker file

void WakeISR(void)
{
  MXC_SEMA->irq0 = MXC_F_SEMA_IRQ0_EN & ~MXC_F_SEMA_IRQ0_CM4_IRQ;
}

void my_timer_initial()
{
    mxc_tmr_cfg_t cfg;
    cfg.pres = MXC_TMR_PRES_32;
    cfg.mode = MXC_TMR_MODE_ONESHOT;
    cfg.bitMode = MXC_TMR_BIT_MODE_32;
    cfg.clock = MXC_TMR_60M_CLK;
    cfg.cmp_cnt = 0xFFFFFFFF;
    cfg.pol = 0;
    MXC_TMR_Init(TMR, &cfg, false);
    MXC_TMR_Start(TMR);
}


int main(void)
{
  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();


  // Configure Timer
  my_timer_initial();
  uint32_t prescale = (TMR->ctrl0 & MXC_F_TMR_REVB_CTRL0_CLKDIV_A) >> MXC_F_TMR_REVB_CTRL0_CLKDIV_A_POS;
  uint32_t timer_clock = MXC_TMR_RevB_GetClockSourceFreq((mxc_tmr_revb_regs_t*)TMR);
  printf("prescale: %lu, timer_clock: %lu\n", prescale, timer_clock);


  MXC_FCR->urvbootaddr = (uint32_t) &__FlashStart_; // Set RISC-V boot address
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_SMPHR); // Enable Semaphore clock
  MXC_NVIC_SetVector(RISCV_IRQn, WakeISR); // Set wakeup ISR

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(4)); // Let debugger interrupt if needed

  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CPU1); // Enable RISC-V clock

  MXC_LP_EnterSleepMode(); // Let RISC-V run

  return 0;
}

